almazmed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main import views as main_views
# from django.conf.urls.i18n import i18n_patterns 
# from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<slug:city>/', include('main.urls')),
    path('choose_city/', main_views.choose_city, name='choose_city'),
    #path('download/(?P<path>.*)$', main_views.download, name="download"),
    path('setlang', main_views.setlang, name="setlang"),
    path('', main_views.domain, name="domain"),
    #path('test/', main_views.test, name="test"),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += i18n_patterns('',
#     (_(r'^dual-lang/'), include('duallang.urls')),
    
# )

main/urls.py
from django.urls import path

from . import views

app_name= "main"
urlpatterns = [
    path('', views.index, name='index'),
    
    path('news', views.news, name='news'),
    
    path('about', views.about, name='about'),
    path('director_blog', views.director_blog, name='director_blog'),
    path('lisences', views.lisences, name='lisences'),
    path('letters', views.letters, name='letters'),
    path('partners', views.partners, name='partners'),
    path('test', views.test, name='test'),
    
    path('patients', views.patients, name='patients'),
    path('serviced_area', views.serviced_area, name='serviced_area'),
    path('drug_supply', views.drug_supply, name='drug_supply'),
    path('gobmp', views.gobmp, name='gobmp'),
    path('osms', views.osms, name='osms'),
    path('question_answer', views.question_answer, name='question_answer'),
    path('goverment_services', views.goverment_services, name='goverment_services'),
    path('public_service_register', views.public_service_register, name='public_service_register'),

    path('news/<int:id>', views.one_new, name='one_new'),

    path('specialists', views.specialists, name='specialists'),
    path('specialists/activity/<int:id>', views.specialists_activity, name='specialists_activity'),
    path('specialists/<int:id>', views.specialist, name='specialist'),

    path('uslugi', views.uslugi, name='uslugi'),
    path('sub_uslugi/<int:id>', views.sub_uslugi, name='sub_uslugi'),
    path('uslugi/<int:id>/choose_doctor', views.choose_doctor, name='choose_doctor'),

    path('search', views.search, name="search"),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),    
    
]
#

main/views.py
from django.shortcuts import render

#from .forms import UserForm, CommentForm, BlogForm
from .models import *

from django.shortcuts import redirect
from django.urls import reverse

#from .modules.hashutils import check_pw_hash, make_pw_hash

#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.utils import timezone

#import smtplib, ssl

#from .modules.sendEmail import send_email
import itertools
from django.http import HttpResponse, JsonResponse, Http404

#from .tokens import account_activation_token
#from django.core.mail import EmailMessage
from django import template
import os
from django.conf import settings

#from django.db.models import Q
from datetime import datetime
#FUNCTIONS
#from django.template.Library import filter
#from django.utils.translation import gettext
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.db.models.functions import Lower

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
COUNT_BLOG_ON_PAGE=50


from django.views.decorators.csrf import csrf_exempt

def get_paginated_blogs(request, paginator):
    page = request.GET.get('page')
    try:
        page = int(page)
    except:
        page = 1
    a = ""
    block = ""
    pages=[]
    if page:
        try:
            block = paginator.page(page)
        except EmptyPage:
            block = paginator.page(paginator.num_pages)
            page = paginator.num_pages

        for i in range(page-2, page+3):
            try:
                a = paginator.page(i)
                pages.append(i)
            except:
                continue
        print(pages)
        if pages[-1] != paginator.num_pages:
            pages.append(paginator.num_pages)

        if pages[0] != 1:
            pages.insert(0, 1)
    else:
        pages = [1,2,3,4,5,paginator.num_pages]
        block = paginator.page(1)
    return block, pages


class make_incrementor(object):
    count = 0

    def __init__(self, start):
        self.count = start

    def inc(self, jump=1):
        self.count += jump
        return self.count

    def res(self):
        self.count = 0
        return self.count

def sort_doctors(city):
    branches = Branch.objects.filter(city=city)
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    all_doctors = []
    for activity in activities:
        doctors = Doctor.objects.filter(direction_of_activity=activity, branch__in=branches)
        if(len(doctors) > 0): 
            all_doctors.append({"activity": activity, "doctors": doctors})
    return all_doctors



def get_parameter(request, name):
    try:
        return request.GET[name]
    except:
        return None 

def post_parameter(request, name):
    try:
        return request.POST[name]
    except:
        return None 

def post_file(request, name):
    try:
        return request.FILES.getlist(name)
    except:
        return None

def session_parameter(request, name):
    try:
        return request.session[name]
    except:
        return None

#VIEWS

def index(request, city):
    news = New.objects.all()[:4]
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    branches = Branch.objects.filter(city=current_city)
    doctors = Doctor.objects.filter(branch__in=branches, has_appointment=True)[:6]
    cities = City.objects.all()
    partners = Partner.objects.all()
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    services_types = ServiceType.objects.filter(name__icontains="Бесплатные", branch__in=branches).first()
    free_services_types = None
    if services_types:
        free_services_types = services_types.services_types.all()[0:4]
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    return render(request, "index.html", {
        "news":news,
        "city": current_city,
        "branches": branches,
        "all_branches": Branch.objects.all(),
        "doctors": doctors,
        "cities": cities,
        "partners": partners,
        "activities": activities,
        "leaders": leaders,
        "current_lang": session_parameter(request,"lang"),
        "services_types": ServiceType.objects.filter(is_top=True, branch__in=branches),
        "free_services_types": free_services_types,
    })

def about(request, city):
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    branches = Branch.objects.filter(city=current_city)
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    current_branch = Branch.objects.filter(city=current_city).first()
    cities = City.objects.all()
    
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    return render(request, "about.html", {
        "path": [{"О поликлинике": request.META.get('PATH_INFO', None)}],
        "leaders": leaders,
        "activities": activities,
        "city": current_city,
        "current_branch": current_branch,
        "cities": cities,
        "current_lang": session_parameter(request,"lang"),
        "services_types": ServiceType.objects.filter(is_top=True, branch__in=branches),
        "branches": branches,
    })

def specialists(request, city):
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    branches = Branch.objects.filter(city=current_city)
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    doctors = sort_doctors(current_city)
    cities = City.objects.all()
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    return render(request, "specialists.html", {
        "path": [{"Специалисты": request.META.get('PATH_INFO', None)}],
        "activities": activities,
        "doctors": doctors,
        "city": current_city,
        "cities": cities,
        "leaders": leaders,
        "current_lang": session_parameter(request,"lang"),
        "services_types": ServiceType.objects.filter(is_top=True, branch__in=branches),
        "branches": branches,
    })

def specialists_activity(request, city, id):
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    current_activity = None
    try:
        current_activity = DirectionOfActivity.objects.get(id=id)
    except:
        return redirect(reverse("main:specialists"))
    branches = Branch.objects.filter(city=current_city)
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    doctors = Doctor.objects.filter(direction_of_activity=current_activity, branch__in=branches)
    all_doctors = [{"activity": current_activity, "doctors": doctors}]
    cities = City.objects.all()
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    return render(request, "specialists.html", {
        "path": [{"Специалисты": "/"+current_city.en_name+"/specialists"}, {current_activity.name: request.META.get('PATH_INFO', None)}],
        "activities": activities,
        "doctors": all_doctors,
        "current_activity": current_activity,
        "city": current_city,
        "cities": cities,
        "leaders": leaders,
        "current_lang": session_parameter(request,"lang"),
        "services_types": ServiceType.objects.filter(is_top=True, branch__in=branches),
        "branches": branches,
    })

def specialist(request, city, id):
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    branches = Branch.objects.filter(city=current_city)
    activities = DirectionOfActivity.objects.filter(branch__in=branches)
    current_doctor = None
    try:
        current_doctor = Doctor.objects.get(id=id)
    except:
        return redirect(reverse("main:index"))
    cities = City.objects.all()
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    return render(request, "specialist.html", {
        "path": [{"Специалисты": "/"+current_city.en_name+"/specialists"}, {current_doctor.fullname: request.META.get('PATH_INFO', None)}],
        "activities": activities,
        "current_doctor": current_doctor,
        "city": current_city,
        "cities": cities,
        "leaders": leaders,
        "current_lang": session_parameter(request,"lang"),
        "services_types": ServiceType.objects.filter(is_top=True, branch__in=branches),
        "branches": branches,
    })

def sub_uslugi(request, city, id):
    current_city = City.objects.filter(en_name=city).first()
    if not current_city:
        return redirect(reverse("main:index", kwargs={"city": City.objects.all().first().en_name}))
    branches = Branch.objects.filter(city=current_city)
    cities = City.objects.all()
    leaders = DirectionOfActivity.objects.filter(name="Руководители", branch__in=branches).first()
    service_type = ServiceType.objects.filter(id=id).first()
    services_types = ServiceType.objects.filter(is_top=True, branch__in=branches)
    parent_service_type = ServiceType.objects.filter(services_types=service_type).first()
    if parent_service_type:
        if not parent_service_type.is_top:
            services_types = parent_service_type.services_types.all()
        else:
            services_types = ServiceType.objects.filter(is_top=True, branch__in=branches)
        parent_service_type2 = ServiceType.objects.filter(services_types=parent_service_type).first()

main/templates/about.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
	<link rel="stylesheet" href="{%static 'css/usugi-styles.css'%}" />
	<link rel="stylesheet" href="{%static 'css/about.css'%}" />
	<script
		src="https://kit.fontawesome.com/b79a50aa67.js"
		crossorigin="anonymous"
	></script>
	<style>
		p {
			margin: 25px 0;
		}
	</style>
	<title>Алмаз Медикал Групп О нас</title>
	<meta name="description" content="Алмаз Медикал Групп {{city.name}} О нас"/>
{% endblock %}



{% block body %}
	<body>
		<div class="main-section">
			<div class="wrapper">
				<div class="row" style="margin-bottom: 59px;">
					<div class="col-md-3 col-sm-3 hidden-xs hidden-sm left-menu-md">
						<div class="sidebar">
							<ul class="sidebar-menu">
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<div class="active opened">
											<span>О поликлинике</span>
										</div>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:specialists_activity' city.en_name leaders.id%}" class="">
											<span>Руководители</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:director_blog' city.en_name%}" class="">
											<span>Блог директора филиала</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:lisences' city.en_name%}" class="">
											<span>Лицензии</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:partners' city.en_name%}" class="">
											<span>Партнеры</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:letters' city.en_name%}">
											<span>Благодарственные письма</span>
										</a>										
									</div>									
								</li>								
							</ul>
						</div>					
					</div>
					
					<div class="col-md-9 col-sm-12 col-xs-12">
						{%if current_branch.image and current_branch.description %}	
							<img src="{{current_branch.image.url}}" width="100%" height="512px" alt="">
							<p style="line-height: 2em;">
								{{current_branch.description|linebreaks}}
							</p>
						{%else%}
							<div style="text-align: center;font-size: 25px;font-weight: 700;">Здесь пока нет информации!</div>
						{%endif%}
					</div>
				</div>							
			</div>
		</div>
	</body>
{% endblock %}

{% block scripts%}
	<!-- SCRIPTS -->
	<script src="js/main.js"></script>
	<script src="js/uslugi.js"></script>
{%endblock%}

main/templates/director_blog.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
	<link rel="stylesheet" href="{%static 'css/usugi-styles.css'%}" />
    <link rel="stylesheet" href="{%static 'css/about.css'%}" />
    <link rel="stylesheet" href="{%static 'css/director_blog.css'%}" />
	<script
		src="https://kit.fontawesome.com/b79a50aa67.js"
		crossorigin="anonymous"
	></script>
	<style>
		p {
			margin: 25px 0;
		}
	</style>
	<title>Алмаз Медикал Групп Блог директора</title>
	<meta name="description" content="Алмаз Медикал Групп {{city.name}}. Блог директора Филиала"/>
{% endblock %}



{% block body %}
	<body>
		<div class="main-section">
			<div class="wrapper">
				<div class="row" style="margin-bottom: 59px;margin-top: 59px;">
					<div class="col-md-3 col-sm-3 hidden-xs hidden-sm left-menu-md">
						<div class="sidebar">
							<ul class="sidebar-menu">
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:about' city.en_name%}">
											<span>О поликлинике</span>
                                        </a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:specialists_activity' city.en_name leaders.id%}" class="">
											<span>Руководители</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<div class="opened active">
											<span>Блог директора филиала</span>
                                        </div>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:lisences' city.en_name%}">
											<span>Лицензии</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:partners' city.en_name%}">
											<span>Партнеры</span>
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:letters' city.en_name%}">
											<span>Благодарственные письма</span>
										</a>										
									</div>									
								</li>								
							</ul>
						</div>					
					</div>
					
					<div class="col-md-9 col-sm-12 col-xs-12">
						<table>
                            <tbody>
                                <tr>
                                    <td valign="top" style="padding-right: 20px;">
                                        <img width="200" src="{%if director.doctor.image%}{{director.doctor.image.url}}{%else%}{%static 'img/photo-not-found.jpg'%}{%endif%}" /> <br />
                                        <span style="font: 11px/20px PT Sans Caption, Arial, sans-serif;">
                                            <b>{{director.doctor.fullname}}</b><br />
                                            Директор филиала ТОО «Almaz Medical Group»
                                        </span>
                                    </td>
                                    <td valign="top">
                                        <h3>{{director.title}}</h3>
                                        {{director.description|linebreaks}}
                                    </td>
                                </tr>
                            </tbody>
                        </table>     
                        <table class="order-block ask-block">
                            <tbody>
                                <tr>
                                    <td class="col-md-9 col-sm-8 col-xs-7 valign">
                                        <div class="text">
                                            <h5>Не нашли ответа на свой вопрос?</h5>
                                            Свяжитесь с нами, и мы предоставим необходимую информацию.
                                        </div>
                                    </td>
                                    <td class="col-md-3 col-sm-4 col-xs-5 valign">
                                        <div class="btns">
                                            <span class="btn btn-default btn-lg animate-load" data-event="jqm" data-param-id="39" data-name="question"><span>Задать вопрос</span></span>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>                                          
					</div>
				</div>							
			</div>
		</div>
	</body>
{% endblock %}

{% block scripts%}
	<!-- SCRIPTS -->
	<script src="js/main.js"></script>
	<script src="js/uslugi.js"></script>
{%endblock%}

main/templates/news.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
	<link rel="stylesheet" href="{%static 'css/news.css'%}">
	<title>Алмаз Медикал Групп Новости</title>
	<meta name="description" content="Алмаз Медикал Групп {{city.name}}. Новости"/>
{% endblock %}



{% block body %}
<body>
		

	<!-- MAIN SECTION -->
	<div class="main-section" id="html">
		<div class="wrapper">
			<div class="row" style="margin-bottom: 59px;">
				<div class="col-md-9">
					<div class="news-top">
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="{%url 'main:news' city.en_name%}">За все время</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2023">2023</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2022">2022</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2021">2021</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2020">2020</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2019">2019</a>
							</div>								
						</div>
						<div class="news-top-block">
							<div class="news-top-block-text">
								<a href="?year=2018">2018</a>
							</div>								
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							{%for new in news%}
								<div class="news-block shadow1 clearfix">
									<div class="news-block-image">
										<a href="{%url 'main:one_new' city.en_name new.id%}">
											<img src="{{new.image.url}}" alt="" class="img-responsive">
										</a>
									</div>
									<div class="news-block-text-block">
										<div class="text-block-top">
											<a href="{%url 'main:one_new' city.en_name new.id%}">{{new.title}}</a>
										</div>
										<div class="new-section__title">
											<a src="">{{new.description|truncatechars:80}}</a>
										</div>
										<div class="text-block-under">
											{{new.date|date:"d F Y"}}
										</div>
										
									</div>
								</div>
							{%endfor%}
						</div>
					</div>
					{%if not news%}
						<div class="nothing">
							Ничего не найдено!
						</div>
					{%endif%}
				</div>
			</div>
		</div>
		
	</div>

	<div class="banner_warning">
		Имеются противопоказания. Необходима консультация специалиста
	</div>
</body>
{% endblock %}

{% block scripts%}
	<!-- SCRIPTS -->
	<script src="{%static 'bootstrap/js/bootstrap.js'%}"></script>
	<script src="{%static 'js/main.js'%}"></script>
	
	<script src="{%static 'js/uslugi.js'%}"></script>
	
{%endblock%}

main/templates/patients.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
	<link rel="stylesheet" href="{%static 'css/usugi-styles.css'%}" />
	<link rel="stylesheet" href="{%static 'css/patients.css'%}" />
    <link rel="stylesheet" href="{%static 'css/about.css'%}" />
	<script
		src="https://kit.fontawesome.com/b79a50aa67.js"
		crossorigin="anonymous"
	></script>
	<style>
		
	</style>
	<title>Алмаз Медикал Групп Клиенту</title>
	<meta name="description" content="Алмаз Медикал Групп {{city.name}}. Вся информация для наших клиентов">
{% endblock %}



{% block body %}
	<body>
		<div class="main-section" style="margin-top: 30px;">
			<div class="wrapper">
				<div class="row" style="margin-bottom: 59px;">
					<div class="col-md-3 col-sm-3 hidden-xs hidden-sm left-menu-md hide-mobile">
						<div class="sidebar">
							<ul class="sidebar-menu">
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:serviced_area' city.en_name%}" >
											Обслуживаемая территория
                                        </a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="https://lkp-zha.dmed.kz/">
											Запись на примем к врачу
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="https://lkp-zha.dmed.kz/">
											Вызов врача на дом
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:drug_supply' city.en_name%}">
											Лекарственное обеспечение
                                        </a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="https://www.kdlolymp.kz/results/login">
											Результаты лабораторных исследований
										</a>										
									</div>									
								</li>
								<li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="https://lkp-zha.dmed.kz/">
											Личный кабинет
										</a>										
									</div>									
                                </li>
                                <li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:gobmp' city.en_name%}">
											ГОБМП
										</a>										
									</div>									
                                </li>
                                <li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:osms' city.en_name%}">
											ОСМС
										</a>										
									</div>									
                                </li>
                                <li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:question_answer' city.en_name%}">
											Вопрос ответ
										</a>										
									</div>									
                                </li>
                                <li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:goverment_services' city.en_name%}">
											Государственные услуги
										</a>										
									</div>									
                                </li>
                                <li class="sidebar-menu__item dropdown-link">
									<div class="sidebar-menu__link dropdown-link">
										<a href="{%url 'main:public_service_register' city.en_name%}">
											Реестр Государственных услуг
										</a>										
									</div>									
								</li>								
							</ul>
						</div>					
					</div>
					
					<div class="col-md-9 col-sm-12 col-xs-12 content-md">
                        <p style="text-align: center;">
                            <img width="1245" src="{%static 'img/patients.jpg'%}" height="480" class="img-responsive" />
                        </p>
                        <p>
                            <b>Клиника «Медицинский центр»</b> – это частный медицинский центр для всей семьи с 3 филиалами в Москве и МО. Основан в 2006 году и за 10 лет из кабинета терапевта превратился в клинику с тремя филиалами, командой единомышленников
                            и современной лабораторией. Лечим взрослых и детей, занимаемся профилактикой болезней и учим быть здоровыми.
                        </p>
                        <p>
                            Главная наша ценность – это команда. У нас работают опытные доктора – терапевты, узкие специалисты, диагносты. Вместе мы вылечили несколько сотен детских ангин и взрослых гастритов, помогли родиться 3 000 детей и провели 20 000 ЭКГ
                            на дому.
                        </p>
                        <h3>Наши направления:<br /></h3>
                        <ul>
                            <li><b>Детское отделение.</b>Заботимся о здоровье ребенка от зачатия до совершеннолетия. В клинике принимают педиатры, детский офтальмолог и хирург-ортопед.</li>
                            <li><b>Взрослое отделение.</b> Первичная консультация и терапия, а также лечение у узких специалистов - кардиолога и гастроэнтеролога.</li>
                            <li><b>Ведение беременности.</b>Деликатный подход к важному событию: поддерживающая терапия, дородовое сопровождение, школа молодых родителей для будущих пап и мам.</li>
                            <li><b>Диагностика.</b> Собственная лаборатория, которая позволит получить результаты анализов день-в-день, без ожидания в очередях.</li>
                            <li><b>Выезд врача на дом.</b> Приедем в любую точку Москвы и МО. Осмотрим, выпишем лечение, возьмем нужные анализы и даже сделаем ЭКГ на дому!</li>
                        </ul>
                        <p>
                            Мы верим, что крепкое здоровье – совместный труд доктора и пациента. Врачи «Медицинского центра» говорят на одном языке, объясняют каждое назначение и никогда не назначают лечение «на всякий случай» или потому, что так принято.
                            <br />
                        </p>
                        <p>
                            Записаться на прием или вызвать врача на дом можно по телефону или онлайн. Сохраните здоровье на долгие годы вместе с клиникой «Медицинский центр»!
                        </p>
                        <br />
                    </div>                    
				</div>							
			</div>
		</div>
	</body>
{% endblock %}

{% block scripts%}
	<!-- SCRIPTS -->
	<script src="js/main.js"></script>
	<script src="js/uslugi.js"></script>
{%endblock%}

main/templates/test.html
<html> 
    <head> 
    <title>Мой</title> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head> 
<body> 
    <div class="translate">Тестирование</p>
    <div class="translate_control" lang="en"></div>

    <script>
    function googleSectionalElementInit() {
      new google.translate.SectionalElement({
        sectionalNodeClassName: 'translate',
        controlNodeClassName: 'translate_control',
        background: '#f4fa58'
      }, 'google_sectional_element');
    }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleSectionalElementInit&ug=section&hl=en"></script>

</body>
</html>